apiVersion: v1
kind: Service
metadata:
  name: recruitment-as-a-service
  namespace: development
spec:
  ports:
    - name: http
      port: 8081
  type: LoadBalancer    
  selector:
    apps: recruitment-service